### ISSUE TITLE
TrezorT: display doesn't react to touch event

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#334] opened 2018-08-27 11:25 UTC
Irregularly issue, not sure how to simulate this behaviour.
It happens when i have permanently connected device and computer goes to sleep. 
After woke up device is still connected according to Bridge and it is reacting to sent messages, it is showing "passphrase_type_request" (selection where to put passphrase) but buttons are not clickable.
The only solution to this is to disconnect/connect again.

**Comment by matejcik** [comment] 2018-08-27 12:36
Confirmed, this happens to me ~once per day when using SSH login. The buttons are displayed but no reaction to touch events. `trezorctl` reports `LIBUSB_ERROR_BUSY` when attempting to connect, but that could be because `trezor-agent` is blocking it; I'll try to confirm when it happens again.

**Comment by Choms** [comment] 2018-08-28 11:32
Same happening to me on the password manager when I forget the trezor T connected overnight, restarting chrome and disconnect/connect trezor solves it. Also is there any progress on #163 ? I feel like a proper auto-locking like the model one has would fix this issue altogether. Cheers!

**Comment by matejcik** [comment] 2018-08-31 13:28
Playing around with a stuck TT. It reacts normally to USB messages - reverts screen on Initialize, responds to pings, returns addresses, etc. It seems that only the touch screen is dead.
Is it possible that the touch layer turns itself off?

**Comment by prusnak** [comment] 2018-08-31 13:44
most probably a duplicate of / very closely related to https://github.com/trezor/trezor-core/issues/295

**Comment by matejcik** [comment] 2018-08-31 14:04
I'm somewhat sure this is something different. There's no unexpected messages. Far as I was able to tell, the behavior is the same as if you didn't actually touch Trezor.

I.e., if you run `trezorctl ping hello -b`, you will see the confirmation dialog and PC is waiting for `Success` message that never comes. Buttons on the screen will not highlight, etc. If you kill the waiting process and rerun it, Trezor will respond to `Initialize` and continue as normal.

**Comment by matejcik** [comment] 2018-09-03 14:56
On a device with debug link enabled, I can continue to use a "frozen" Trezor by using the debug link instead of clicking/swiping.

**Comment by matejcik** [comment] 2018-09-05 13:40
I built a modified firmware that calls `touch_init()` (from https://github.com/trezor/trezor-core/blob/v2.0.7/embed/trezorhal/touch.c#L42) when asked to.

When this is invoked on a frozen Trezor, the touch screen starts responding again.

I'll try to run firmware from master, where there are apparently some changes WRT touchscreen initialization?

**Comment by matejcik** [comment] 2018-09-10 15:39
With a modified 2.0.8 firmware, calling `touch_power_on()` does not awaken the touchscreen, but cycling `touch_power_off()` and then `touch_power_on()` does.

**Comment by sammy007** [comment] 2018-09-23 17:27
Same on OSX, device left connected for a while then I can't confirm payment via UI bc it does not react to touch event.

**Comment by mang-design** [comment] 2018-09-24 15:03
I honestly wasn't sure if it was a feature or a bug. Getting the same issue on Kubuntu 18.04 (Kernel 4.15.0-34).

**Comment by matejcik** [comment] 2018-10-12 14:11
It seems that the issue is not present in 2.0.6

This is not fully confirmed yet, but I am usually able to hit the issue at least once a day, and I haven't seen it with 2.0.6 since yesterday.

**Comment by matejcik** [comment] 2018-11-15 15:24
Let's update this issue with what we know so far.

The "lost touch" manifests itself as reading all-ones from the I2C bus. The bus is pull-up so this means that the opposite side is not writing to it. There might be several reasons for that, one of which is desynchronized SCLK tick.

Curious to note is that the all-ones condition happens frequently during normal operation, but usually it resolves itself - either right on the next read attempt, or after ~25ms downtime.

The i2c bus is configured for 400kHz, which is its specified maximum, but lowering to 200kHz does not help.

When the touch finally gets stuck, I tried restarting the i2c controller, repeating the power-on sequence afterwards, but the only thing that helps is full reset of the touch controller.

Notably it seems that the failures only appear when the touch controller drops to Monitor (low-power) mode. Disabling its power management seems to make them go away. This would hint that the problem actually is caused by the hibernation mode, which is undocumented and maybe turns itself on randomly :)

I'll be doing more tests, and also trying to reproduce the issue with power management off; if that helps, we'll probably use that.

**Comment by matejcik** [comment] 2018-11-15 16:52
when the i2c bus is running at 400kHz, the faults also happen in 397ms durations. i have not observed that with 200kHz clock.

any ideas what's interesting about 397 ms ?

**Comment by matejcik** [comment] 2018-11-16 17:13
I've run into what looks very much like an electrical issue: after some time the touch controller seems to just ... up and ... reset. It re-enables power management and the drops start to happen again.

(I've seen this behavior before, with TC spontaneously switching from interrupt-polling to interrupt-trigger mode; I assumed that this can happen when power saving kicks in, but apparently not.)

=> notably, what's interesting about 300some ms is that's how long it takes for the touch controller to reboot.

This problem does NOT depend on:
- what cable is used
- whether the device is plugged directly into a PC or through a hub
- i2c bus clock speed
(interestingly though, i'm still not seeing the ~300ms drops with the lower i2c clock speed)

There are times when the problem manifests more frequently and other times when it happens less. So, uh, ambient temperature?

**Comment by matejcik** [comment] 2018-11-16 18:59
I suspect that the device simply doesn't like that we poll it so much.
When reading in an endless loop, I see stalls and resets.
When reading with 5ms delays interspersed, things seem stable.

Counterpoint to this: when *not* in an endless loop, adding a 5ms delay before read attempt doesn't prevent the stalls.
BUT, it seems to prevent the resets.

Frequent polling goes contrary to the data sheet too; we're supposed to wait for interrupts and then read data as it comes off the i2c bus.

A simple fix - checking whether the interrupt line is down before reading - seems to help too, except in that case we drop packets. But I have a workaround in mind for that.

**Comment by prusnak** [comment] 2018-11-30 15:07
Shouldn't we close this after https://github.com/trezor/trezor-core/pull/420 merge?

**Comment by matejcik** [comment] 2018-11-30 15:47
Probably, yes. We can reopen if it turns out that #420 didn't fix this.

**Closed** 2018-11-30 16:21 UTC
Labels: bug, hardware
