### ISSUE TITLE
"Hold to confirm" broken in debug mode

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-core#419] opened 2018-11-21 14:25 UTC
This is somewhat visible on emulator and very noticeable on actual device with debugging enabled.

To reproduce: open a "wipe device" screen and move your mouse/finger over the Hold button. The progress bar will not update while the cursor is moving.

AFAICT this is because display doesn't update while processing touch events, and with debug firmware it's slow enough to prevent display updates completely?

What's even worse: in the "reset device" flow, it's possible (and rather easy on real HW) to just click on the Hold button and it stays pressed down until you touch the device again. It seems to be dropping "end touch" events or something.

**Comment by jpochyla** [comment] 2019-01-11 14:36
Reproduced. The button task seems to be suffocating the loader-rendering task. I'll look into it.

**Comment by jpochyla** [comment] 2019-01-17 15:59
Fixed in 305a364

**Closed by jpochyla** 2019-01-17 15:59 UTC
Labels: bug, firmware, ui
